<?php

return [
    ["宿泊施設マネージャー", "Accommodation and Hospitality Managers nec", "STSOL", "VETASSESS"],
    ["会計士（一般）	", "	Accountant (General)", "MLTSSL", "CAANZ/CPAA/IPA"],
    ["アクチュアリー	", "	Actuary	", "MLTSSL", "VETASSESS"],
    ["鍼灸師	", "	Acupuncturist	", "STSOL", "	Chinese Medicine Board of Australia	"],
    ["宣伝部長	", "	Advertising Manager	", "STSOL", "AIM"],
    ["広告スペシャリスト	", "	Advertising Specialist	", "STSOL", "VETASSESS"],
    ["航空エンジニア	", "	Aeronautical Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["飛行機のパイロット	", "	Aeroplane Pilot	", "Regional", "	CASA	"],
    ["農業コンサルタント	", "	Agricultural Consultant	", "MLTSSL", "VETASSESS"],
    ["農業エンジニア", "	Agricultural Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["農業科学者", "	Agricultural Scientist	", "MLTSSL", "VETASSESS"],
    ["農業技術者", "	Agricultural Technician	", "Regional", "VETASSESS"],
    ["エアコンと機械サービス配管工", "	Airconditioning and Mechanical Services Plumber	", "MLTSSL", "	TRA	"],
    ["エアコンおよび冷凍機械工", "	Airconditioning and Refrigeration Mechanic	", "MLTSSL", "	TRA	"],
    ["航空機メンテナンスエンジニア（航空電子工学）	", "	Aircraft Maintenance Engineer (Avionics)	", "STSOL", "	TRA	"],
    ["航空機メンテナンスエンジニア（機械）	", "	Aircraft Maintenance Engineer (Mechanical)	", "STSOL", "	TRA	"],
    ["航空機メンテナンスエンジニア（構造物）	", "	Aircraft Maintenance Engineer (Structures)	", "STSOL", "	TRA	"],
    ["救急隊員	", "	Ambulance Officer	", "STSOL", "VETASSESS"],
    ["アミューズメントセンターマネージャー	", "	Amusement Centre Manager	", "Regional", "VETASSESS"],
    ["麻酔技術者", "	Anaesthetic Technician	", "STSOL", "VETASSESS"],
    ["麻酔医", "	Anaesthetist	", "STSOL", "	MedBA	"],
    ["アナリストプログラマー	", "	Analyst Programmer	", "MLTSSL", "	ACS	"],
    ["動物アテンダント/トレーナー", "	Animal Attendants and Trainers nec	", "STSOL", "VETASSESS"],
    ["養蜂家", "	Apiarist	", "STSOL", "VETASSESS"],
    ["水産養殖農家	", "	Aquaculture Farmer	", "STSOL", "VETASSESS"],
    ["樹医", "	Arborist	", "STSOL", "	TRA	"],
    ["建築家", "	Architect	", "MLTSSL", "	AACA	"],
    ["建築製図者", "	Architectural Draftsperson	", "STSOL", "VETASSESS"],
    ["建築・建築・測量技術者", "	Architectural, Building and Surveying Technicians nec	", "STSOL", "VETASSESS"],
    ["芸術教師（私立授業）	", "	Art Teacher (Private Tuition)	", "STSOL", "VETASSESS"],
    ["アートディレクター	", "	Artistic Director	", "STSOL", "VETASSESS"],
    ["芸術管理者/マネージャ	", "	Arts Administrator or Manager	", "STSOL", "VETASSESS"],
    ["聴覚医	", "	Audiologist	", "MLTSSL", "VETASSESS"],
    ["自動車電気工", "	Automotive Electrician	", "MLTSSL", "	TRA	"],
    ["パン類製造業者", "	Baker	", "STSOL", "	TRA	"],
    ["バリスター	", "	Barrister	", "MLTSSL", "	A legal admissions authority of a State or Territory	"],
    ["畜産農家", "	Beef Cattle Farmer	", "STSOL", "VETASSESS"],
    ["生化学者", "	Biochemist	", "MLTSSL", "VETASSESS"],
    ["バイオメディカルエンジニア	", "	Biomedical Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["バイオテクノロジー	", "	Biotechnologist	", "MLTSSL", "VETASSESS"],
    ["ボートビルダー/修繕者", "	Boat Builder and Repairer	", "MLTSSL", "	TRA	"],
    ["編集者", "	Book or Script Editor	", "STSOL", "VETASSESS"],
    ["植物学者	", "	Botanist	", "MLTSSL", "VETASSESS"],
    ["れんが職人", "	Bricklayer	", "MLTSSL", "	TRA	"],
    ["建築技術者", "	Building and Engineering Technicians nec	", "Regional", "VETASSESSEngineers Australia	"],
    ["ビル調査官", "	Building Inspector	", "STSOL", "VETASSESS"],
    ["ビジネスマシンメカニック	", "	Business Machine Mechanic	", "STSOL", "	TRA	"],
    ["食肉解体処理作業員", "	Butcher or Smallgoods Maker	", "STSOL", "	TRA	"],
    ["キャビネットメーカー	", "	Cabinetmaker	", "MLTSSL", "	TRA	"],
    ["ケーブル工（データ・通信）	", "	Cabler (Data and Telecommunications)	", "STSOL", "	TRA	"],
    ["カフェまたはレストランマネージャー	", "	Cafe or Restaurant Manager	", "STSOL", "VETASSESS"],
    ["カメラオペレーター（映画、テレビ、ビデオ）	", "	Camera Operator (Film, Television or Video)	", "STSOL", "	TRA	"],
    ["キャラバンパークとキャンプ場のマネージャー	", "	Caravan Park and Camping Ground Manager	", "Regional", "VETASSESS"],
    ["心臓技術者	", "	Cardiac Technician	", "STSOL", "VETASSESS"],
    ["心臓病学者	", "	Cardiologist	", "MLTSSL", "	MedBA	"],
    ["胸腔鏡外科医	", "	Cardiothoracic Surgeon	", "MLTSSL", "	MedBA	"],
    ["キャリアカウンセラー	", "	Careers Counsellor	", "STSOL", "VETASSESS"],
    ["大工	", "	Carpenter	", "MLTSSL", "	TRA	"],
    ["大工/建具屋	", "	Carpenter and Joiner	", "MLTSSL", "	TRA	"],
    ["地図製作者", "	Cartographer	", "MLTSSL", "VETASSESS"],
    ["シェフ	", "	Chef	", "MLTSSL", "	TRA	"],
    ["化学エンジニア	", "	Chemical Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["化学プラントオペレーター	", "	Chemical Plant Operator	", "STSOL", "	TRA	"],
    ["化学者	", "	Chemist	", "MLTSSL", "VETASSESS"],
    ["化学技術者	", "	Chemistry Technician	", "STSOL", "VETASSESS"],
    ["チーフエグゼクティブ/マネージングディレクター	", "	Chief Executive or Managing Director	", "MLTSSL", "AIM"],
    ["チーフインフォメーションオフィサー	", "	Chief Information Officer	", "MLTSSL", "	ACS	"],
    ["チャイルドケアセンターマネージャー	", "	Child Care Centre Manager	", "MLTSSL", "	TRA	"],
    ["カイロプラクティック	", "	Chiropractor	", "MLTSSL", "	CCEA	"],
    ["映画館/シアターマネージャー	", "	Cinema or Theatre Manager	", "Regional", "VETASSESS"],
    ["土木技師	", "	Civil Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["土木工事ドラフト担当者	", "	Civil Engineering Draftsperson	", "MLTSSL", "	Engineers AustraliaVETASSESS"],
    ["土木工学者	", "	Civil Engineering Technician	", "MLTSSL", "VETASSESS"],
    ["臨床コーダ	", "	Clinical Coder	", "Regional", "VETASSESS"],
    ["臨床血液学者", "	Clinical Haematologist	", "MLTSSL", "	MedBA	"],
    ["臨床心理士	", "	Clinical Psychologist	", "MLTSSL", "	APS	"],
    ["商品トレーダー	", "	Commodities Trader	", "STSOL", "VETASSESS"],
    ["コミュニティアートワーカー	", "	Community Arts Worker	", "Regional", "VETASSESS"],
    ["コミュニティワーカー	", "	Community Worker	", "STSOL", "ACWA"],
    ["会社秘書	", "	Company Secretary	", "STSOL", "VETASSESS"],
    ["補完的健康セラピスト", "	Complementary Health Therapists nec	", "STSOL", "VETASSESS"],
    ["コンピュータネットワークおよびシステムエンジニア	", "	Computer Network and Systems Engineer	", "MLTSSL", "	ACS	"],
    ["会議およびイベント主催者	", "	Conference and Event Organiser	", "STSOL", "VETASSESS"],
    ["コンサベーションオフィサー	", "	Conservation Officer	", "Regional", "VETASSESS"],
    ["保守士	", "	Conservator	", "MLTSSL", "VETASSESS"],
    ["建設見積り者", "	Construction Estimator	", "Regional", "VETASSESS"],
    ["建設プロジェクトマネージャー	", "	Construction Project Manager	", "MLTSSL", "VETASSESS"],
    ["契約管理者	", "	Contract Administrator	", "STSOL", "VETASSESS"],
    ["調理師/コック", "	Cook	", "STSOL", "	TRA	"],
    ["コピーライター	", "	Copywriter	", "STSOL", "VETASSESS"],
    ["コーポレートゼネラルマネージャー	", "	Corporate General Manager	", "MLTSSL", "AIM"],
    ["コーポレートサービスマネージャー	", "	Corporate Services Manager	", "STSOL", "VETASSESS"],
    ["コットン栽培者", "	Cotton Grower	", "STSOL", "VETASSESS"],
    ["カウンセラー	", "	Counsellors nec	", "STSOL", "VETASSESS"],
    ["作物農家", "	Crop Farmers nec	", "STSOL", "VETASSESS"],
    ["カスタマーサービスマネージャー	", "	Customer Service Manager	", "STSOL", "VETASSESS"],
    ["酪農家酪農家	", "	Dairy Cattle Farmer	", "STSOL", "VETASSESS"],
    ["ダンス教師（私立授業）	", "	Dance Teacher (Private Tuition)	", "STSOL", "VETASSESS"],
    ["ダンサーまたは振付家	", "	Dancer or Choreographer	", "STSOL", "VETASSESS"],
    ["データベース管理者	", "	Database Administrator	", "STSOL", "	ACS	"],
    ["歯科衛生士	", "	Dental Hygienist	", "Regional", "VETASSESS"],
    ["歯科専門医	", "	Dental Specialist	", "STSOL", "	ADC	"],
    ["歯科技工士	", "	Dental Technician	", "STSOL", "	TRA	"],
    ["歯科セラピスト	", "	Dental Therapist	", "Regional", "VETASSESS"],
    ["歯科医	", "	Dentist	", "STSOL", "	ADC	"],
    ["皮膚科医	", "	Dermatologist	", "MLTSSL", "	MedBA	"],
    ["開発者プログラマー	", "	Developer Programmer	", "MLTSSL", "	ACS	"],
    ["放射線科医	", "	Diagnostic and Interventional Radiologist	", "MLTSSL", "	MedBA	"],
    ["ディーゼル・モーター技術者	", "	Diesel Motor Mechanic	", "MLTSSL", "	TRA	"],
    ["栄養士	", "	Dietitian	", "STSOL", "	DAA	"],
    ["監督（映画、テレビ、ラジオ、ステージ）", "Director (Film, Television,	Radio or Stage)", "STSOL", "VETASSESS"],
    ["障害者サービス責任者	", "	Disabilities Services Officer	", "STSOL", "VETASSESS"],
    ["ダイバージョナルセラピスト	", "	Diversional Therapist	", "STSOL", "VETASSESS"],
    ["ダイビングインストラクター（屋外）", "	Diving Instructor (Open Water)	", "STSOL", "VETASSESS"],
    ["犬のトレーナー	", "	Dog Handler or Trainer	", "STSOL", "VETASSESS"],
    ["下水道工事者", "	Drainer	", "MLTSSL", "	TRA	"],
    ["ドレスメーカーまたはテーラー	", "	Dressmaker or Tailor	", "STSOL", "	TRA	"],
    ["ドライビングインストラクター	", "	Driving Instructor	", "Regional", "VETASSESS"],
    ["薬物/アルコールカウンセラー	", "	Drug and Alcohol Counsellor	", "STSOL", "VETASSESS"],
    ["幼児期（プレ・小学校前期）教師	", "	Early Childhood (Pre-primary School) Teacher	", "MLTSSL", "	AITSL	"],
    ["地球科学技術者	", "	Earth Science Technician	", "STSOL", "VETASSESS"],
    ["エコノミスト	", "	Economist	", "MLTSSL", "VETASSESS"],
    ["教育顧問	", "	Education Adviser	", "STSOL", "VETASSESS"],
    ["教育マネージャー", "	Education Managers nec	", "STSOL", "VETASSESS"],
    ["教育心理学者	", "	Educational Psychologist	", "MLTSSL", "	APS	"],
    ["電気技師	", "	Electrical Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["電気工学ドラフト担当者	", "	Electrical Engineering Draftsperson	", "MLTSSL", "	Engineers Australia	"],
    ["電気工学技術者	", "	Electrical Engineering Technician	", "MLTSSL", "	TRA	"],
    ["電気ラインワーカー	", "	Electrical Linesworker	", "Regional", "	TRA	"],
    ["電気（一般）	", "	Electrician (General)	", "MLTSSL", "	TRA	"],
    ["電気（スペシャルクラス）	", "	Electrician (Special Class)	", "MLTSSL", "	TRA	"],
    ["電子機器取引労働者	", "	Electronic Equipment Trades Worker	", "MLTSSL", "	TRA	"],
    ["電子機器取引労働者（一般）	", "	Electronic Instrument Trades Worker (General)	", "MLTSSL", "	TRA	"],
    ["電子機器取引労働者（特別クラス）	", "	Electronic Instrument Trades Worker (Special Class)	", "MLTSSL", "	TRA	"],
    ["エレクトロニクス・エンジニア	", "	Electronics Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["救急医療専門医	", "	Emergency Medicine Specialist	", "MLTSSL", "	MedBA	"],
    ["緊急サービスワーカー	", "	Emergency Service Worker	", "Regional", "VETASSESS"],
    ["内分泌学者	", "	Endocrinologist	", "MLTSSL", "	MedBA	"],
    ["技術管理者	", "	Engineering Manager	", "MLTSSL", "	Engineers AustraliaAIM"],
    ["エンジニアリングプロフェッショナル", "	Engineering Professionals nec	", "MLTSSL", "	Engineers Australia	"],
    ["エンジニアリング技術者	", "	Engineering Technologist	", "MLTSSL", "	Engineers Australia	"],
    ["認定看護師", "	Enrolled Nurse	", "STSOL", "	ANMAC	"],
    ["環境コンサルタント	", "	Environmental Consultant	", "MLTSSL", "VETASSESS"],
    ["環境エンジニア	", "	Environmental Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["環境保健担当者	", "	Environmental Health Officer	", "Regional", "VETASSESS"],
    ["環境マネージャー	", "	Environmental Manager	", "MLTSSL", "VETASSESS"],
    ["環境研究科学者	", "	Environmental Research Scientist	", "MLTSSL", "VETASSESS"],
    ["環境科学者", "	Environmental Scientists nec	", "MLTSSL", "VETASSESS"],
    ["運動生理学者	", "	Exercise Physiologist	", "Regional", "VETASSESS"],
    ["外部監査人	", "	External Auditor	", "MLTSSL", "CAANZ/CPAA/IPA"],
    ["施設管理者	", "	Facilities Manager	", "STSOL", "VETASSESS"],
    ["学部長", "	Faculty Head	", "MLTSSL", "VETASSESS"],
    ["家族と婚姻カウンセラー	", "	Family and Marriage Counsellor	", "STSOL", "VETASSESS"],
    ["家族支援労働者	", "	Family Support Worker	", "STSOL", "VETASSESS"],
    ["馬医者", "	Farrier	", "STSOL", "	TRA	"],
    ["ファッションデザイナー	", "	Fashion Designer	", "STSOL", "VETASSESS"],
    ["繊維プラストラー	", "	Fibrous Plasterer	", "MLTSSL", "	TRA	"],
    ["フィルム/ビデオエディタ	", "	Film and Video Editor	", "STSOL", "VETASSESS"],
    ["ファイナンスブローカー	", "	Finance Broker	", "STSOL", "VETASSESS"],
    ["財務マネージャー	", "	Finance Manager	", "STSOL", "CAANZ/CPAA/IPA"],
    ["金融ブローカー", "	Financial Brokers nec	", "STSOL", "VETASSESS"],
    ["ファイナンシャルディーラー", "	Financial Dealers nec	", "STSOL", "VETASSESS"],
    ["金融機関支店長	", "	Financial Institution Branch Manager	", "Regional", "VETASSESS"],
    ["金融・投資アドバイザー	", "	Financial Investment Adviser	", "STSOL", "VETASSESS"],
    ["金融資産運用マネージャー	", "	Financial Investment Manager	", "STSOL", "VETASSESS"],
    ["金融市場ディーラー	", "	Financial Market Dealer	", "STSOL", "VETASSESS"],
    ["応急手当トレーナー", "	First Aid Trainer	", "Regional", "VETASSESS"],
    ["フィットネスセンターマネージャー	", "	Fitness Centre Manager	", "Regional", "VETASSESS"],
    ["組み立て工（一般）	", "	Fitter (General)	", "MLTSSL", "	TRA	"],
    ["組み立て工/ろくろ工", "	Fitter and Turner	", "MLTSSL", "	TRA	"],
    ["組み立て工/溶接工	", "	Fitter-Welder	", "MLTSSL", "	TRA	"],
    ["客室乗務員	", "	Flight Attendant	", "Regional", "VETASSESS"],
    ["床仕上げ工", "	Floor Finisher	", "Regional", "	TRA	"],
    ["花屋", "	Florist	", "STSOL", "	TRA	"],
    ["花の栽培者	", "	Flower Grower	", "STSOL", "VETASSESS"],
    ["フライングインストラクター	", "	Flying Instructor	", "Regional", "VETASSESS"],
    ["食品技術者	", "	Food Technologist	", "MLTSSL", "VETASSESS"],
    ["フットボール選手", "	Footballer	", "STSOL", "VETASSESS"],
    ["林業家", "	Forester	", "MLTSSL", "VETASSESS"],
    ["果物またはナッツ栽培者	", "	Fruit or Nut Grower	", "STSOL", "VETASSESS"],
    ["葬儀労働者", "	Funeral Workers nec	", "Regional", "VETASSESS"],
    ["家具仕上げ人", "	Furniture Finisher	", "STSOL", "	TRA	"],
    ["ギャラリーまたは博物館主事", "	Gallery or Museum Curator	", "STSOL", "VETASSESS"],
    ["ガーデナー（一般）	", "	Gardener (General)	", "STSOL", "	TRA	"],
    ["ガスまたは石油オペレーター	", "	Gas or Petroleum Operator	", "Regional", "	TRA	"],
    ["ガスフィッター	", "	Gasfitter	", "MLTSSL", "	TRA	"],
    ["胃腸科医	", "	Gastroenterologist	", "MLTSSL", "	MedBA	"],
    ["一般開業医	", "	General Practitioner	", "MLTSSL", "	MedBA	"],
    ["地質学者	", "	Geologist	", "STSOL", "VETASSESS"],
    ["地球物理学者	", "	Geophysicist	", "MLTSSL", "VETASSESS"],
    ["地盤工学", "	Geotechnical Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["ガラス工	", "	Glazier	", "MLTSSL", "	TRA	"],
    ["穀物、油糧種子または牧草生産者	", "	Grain, Oilseed or Pasture Grower	", "STSOL", "VETASSESS"],
    ["ブドウ栽培者	", "	Grape Grower	", "STSOL", "VETASSESS"],
    ["グラフィックデザイナー	", "	Graphic Designer	", "STSOL", "VETASSESS"],
    ["グリーンキーパー	", "	Greenkeeper	", "STSOL", "	TRA	"],
    ["体操コーチまたはインストラクター	", "	Gymnastics Coach or Instructor	", "STSOL", "VETASSESS"],
    ["ヘアドライヤー	", "	Hairdresser	", "STSOL", "	TRA	"],
    ["ハードウェア技術者	", "	Hardware Technician	", "STSOL", "	TRA	"],
    ["保健福祉サービスマネージャー", "	Health and Welfare Services Managers nec	", "STSOL", "VETASSESS"],
    ["健康診断および昇進の専門家", "	Health Diagnostic and Promotion Professionals nec	", "STSOL", "VETASSESS"],
    ["健康情報マネージャー	", "	Health Information Manager	", "STSOL", "VETASSESS"],
    ["健康促進役員	", "	Health Promotion Officer	", "STSOL", "VETASSESS"],
    ["ヘリコプターパイロット	", "	Helicopter Pilot	", "Regional", "	CASA	"],
    ["ホースブリーダー	", "	Horse Breeder	", "Regional", "VETASSESS"],
    ["乗馬コーチまたはインストラクター	", "	Horse Riding Coach or Instructor	", "STSOL", "VETASSESS"],
    ["ホーストレーナー	", "	Horse Trainer	", "MLTSSL", "	TRA	"],
    ["病院の薬剤師	", "	Hospital Pharmacist	", "STSOL", "	APharmC	"],
    ["ホテルまたはモーテルマネージャー	", "	Hotel or Motel Manager	", "STSOL", "VETASSESS"],
    ["人事アドバイザー	", "	Human Resource Adviser	", "Regional", "VETASSESS"],
    ["人事部長	", "	Human Resource Manager	", "STSOL", "AIM"],
    ["水理学者	", "	Hydrogeologist	", "MLTSSL", "VETASSESS"],
    ["ICTアカウントマネージャー	", "	ICT Account Manager	", "STSOL", "VETASSESS"],
    ["ICTビジネスアナリスト	", "	ICT Business Analyst	", "MLTSSL", "	ACS	"],
    ["ICTビジネス開発マネージャー	", "	ICT Business Development Manager	", "STSOL", "VETASSESS"],
    ["ICTカスタマーサポートオフィサー	", "	ICT Customer Support Officer	", "STSOL", "	TRA	"],
    ["ICTマネージャーnec 	", "	ICT Managers nec	", "STSOL", "	ACS	"],
    ["ICTプロジェクトマネージャー	", "	ICT Project Manager	", "STSOL", "	ACS	"],
    ["ICT品質保証エンジニア	", "	ICT Quality Assurance Engineer	", "STSOL", "	ACS	"],
    ["ICT営業担当者	", "	ICT Sales Representative	", "STSOL", "VETASSESS"],
    ["ICTセキュリティスペシャリスト	", "	ICT Security Specialist	", "MLTSSL", "	ACS	"],
    ["ICTサポート/テストエンジニア", "	ICT Support and Test Engineers nec	", "STSOL", "	ACS	"],
    ["ICTサポートエンジニア	", "	ICT Support Engineer	", "STSOL", "	ACS	"],
    ["ICTサポート技術者nec 	", "	ICT Support Technicians nec	", "STSOL", "	TRA	"],
    ["ICTシステムテストエンジニア	", "	ICT Systems Test Engineer	", "STSOL", "	ACS	"],
    ["ICTトレーナー	", "	ICT Trainer	", "STSOL", "	ACS	"],
    ["イラストレーター	", "	Illustrator	", "STSOL", "VETASSESS"],
    ["工業デザイナー	", "	Industrial Designer	", "STSOL", "VETASSESS"],
    ["産業エンジニア	", "	Industrial Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["産業薬師", "	Industrial Pharmacist	", "STSOL", "VETASSESS"],
    ["情報と組織の専門家", "	Information and Organisation Professionals nec	", "STSOL", "VETASSESS"],
    ["保険代理店	", "	Insurance Agent	", "STSOL", "VETASSESS"],
    ["保険ブローカー	", "	Insurance Broker	", "STSOL", "VETASSESS"],
    ["保険損失調整	", "	Insurance Loss Adjuster	", "STSOL", "VETASSESS"],
    ["知的財産権弁護士	", "	Intellectual Property Lawyer	", "Regional", "VETASSESS"],
    ["集中治療救急救命救急センター	", "	Intensive Care Ambulance Paramedic	", "STSOL", "VETASSESS"],
    ["集中治療専門医	", "	Intensive Care Specialist	", "MLTSSL", "	MedBA	"],
    ["インテリアデザイナー	", "	Interior Designer	", "STSOL", "VETASSESS"],
    ["内部監査人	", "	Internal Auditor	", "MLTSSL", "VETASSESS"],
    ["通訳	", "	Interpreter	", "STSOL", "	NAATI	"],
    ["ジュエラー	", "	Jeweller	", "STSOL", "	TRA	"],
    ["ジュエリーデザイナー	", "	Jewellery Designer	", "STSOL", "VETASSESS"],
    ["騎手	", "	Jockey	", "Regional", "	TRA	"],
    ["ジョイナー	", "	Joiner	", "MLTSSL", "	TRA	"],
    ["ジャーナリストと他の作家nec 	", "	Journalists and Other Writers nec	", "STSOL", "VETASSESS"],
    ["司法およびその他の法律専門家nec 	", "	Judicial and Other Legal Professionals nec	", "STSOL", "VETASSESS"],
    ["研究室マネージャー	", "	Laboratory Manager	", "STSOL", "VETASSESS"],
    ["土地エコノミスト	", "	Land Economist	", "MLTSSL", "VETASSESS"],
    ["ランドスケープアーキテクト	", "	Landscape Architect	", "MLTSSL", "VETASSESS"],
    ["ランドスケープガーデン	", "	Landscape Gardener	", "STSOL", "	TRA	"],
    ["リエゾンオフィサー	", "	Liaison Officer	", "Regional", "VETASSESS"],
    ["図書館員	", "	Librarian	", "STSOL", "VETASSESS"],
    ["図書館の技術者	", "	Library Technician	", "STSOL", "VETASSESS"],
    ["ライフサイエンステクニシャン	", "	Life Science Technician	", "STSOL", "VETASSESS"],
    ["ライフサイエンス（一般）	", "	Life Scientist (General)	", "MLTSSL", "VETASSESS"],
    ["生命科学者", "	Life Scientists nec	", "MLTSSL", "VETASSESS"],
    ["リフトメカニック	", "	Lift Mechanic	", "MLTSSL", "	TRA	"],
    ["家畜農家", "	Livestock Farmers nec	", "STSOL", "VETASSESS"],
    ["錠前屋", "	Locksmith	", "MLTSSL", "	TRA	"],
    ["メンテナンスプランナー	", "	Maintenance Planner	", "Regional", "VETASSESS"],
    ["メイクアップアーティスト	", "	Make Up Artist	", "STSOL", "	TRA	"],
    ["管理会計	", "	Management Accountant	", "MLTSSL", "CAANZ/CPAA/IPA"],
    ["経営コンサルタント	", "	Management Consultant	", "MLTSSL", "VETASSESS"],
    ["メーカー	", "	Manufacturer	", "STSOL", "VETASSESS"],
    ["海洋生物学者	", "	Marine Biologist	", "MLTSSL", "VETASSESS"],
    ["マーケットリサーチアナリスト	", "	Market Research Analyst	", "Regional", "VETASSESS"],
    ["マーケティングスペシャリスト	", "	Marketing Specialist	", "STSOL", "VETASSESS"],
    ["マッサージセラピスト	", "	Massage Therapist	", "STSOL", "VETASSESS"],
    ["材料エンジニア	", "	Materials Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["数学者	", "	Mathematician	", "STSOL", "VETASSESS"],
    ["肉の検査官	", "	Meat Inspector	", "STSOL", "VETASSESS"],
    ["機械工学士	", "	Mechanical Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["機械工学ドラフト担当者	", "	Mechanical Engineering Draftsperson	", "Regional", "	Engineers Australia	"],
    ["機械技術者	", "	Mechanical Engineering Technician	", "STSOL", "	TRA	"],
    ["医療管理者	", "	Medical Administrator	", "Regional", "VETASSESS"],
    ["医療診断用レントゲン技師", "	Medical Diagnostic Radiographer	", "MLTSSL", "	ASMIRT	"],
    ["メディカルラボ科学者	", "	Medical Laboratory Scientist	", "MLTSSL", "AIMS"],
    ["医療検査技師	", "	Medical Laboratory Technician	", "STSOL", "AIMS"],
    ["医療腫瘍学者	", "	Medical Oncologist	", "MLTSSL", "	MedBA	"],
    ["医療従事者", "	Medical Practitioners nec	", "MLTSSL", "	MedBA	"],
    ["医療放射線セラピスト	", "	Medical Radiation Therapist	", "MLTSSL", "	ASMIRT	"],
    ["医療技術者", "	Medical Technicians nec	", "STSOL", "VETASSESS"],
    ["金属製作者	", "	Metal Fabricator	", "MLTSSL", "	TRA	"],
    ["金属組み立て工", "	Metal Fitters and Machinists nec	", "STSOL", "	TRA	"],
    ["金属工（ファーストクラス）	", "	Metal Machinist (First Class)	", "MLTSSL", "	TRA	"],
    ["冶金または材料技術者	", "	Metallurgical or Materials Technician	", "STSOL", "VETASSESS"],
    ["冶金学	", "	Metallurgist	", "MLTSSL", "VETASSESS"],
    ["気象学者	", "	Meteorologist	", "MLTSSL", "VETASSESS"],
    ["微生物学者	", "	Microbiologist	", "MLTSSL", "VETASSESS"],
    ["中学校教師	", "	Middle School Teacher	", "STSOL", "	AITSL	"],
    ["助産師	", "	Midwife	", "MLTSSL", "	ANMAC	"],
    ["鉱山副	", "	Mine Deputy	", "STSOL", "VETASSESS"],
    ["鉱業エンジニア（石油を除く）	", "	Mining Engineer (excluding Petroleum)	", "MLTSSL", "	Engineers Australia	"],
    ["宗教家", "	Minister of Religion	", "STSOL", "VETASSESS"],
    ["混合作物と家畜農家	", "	Mixed Crop and Livestock Farmer	", "STSOL", "VETASSESS"],
    ["混合作物農家	", "	Mixed Crop Farmer	", "STSOL", "VETASSESS"],
    ["混合畜産農家	", "	Mixed Livestock Farmer	", "STSOL", "VETASSESS"],
    ["モーターメカニック（一般）	", "	Motor Mechanic (General)	", "MLTSSL", "	TRA	"],
    ["オートバイのメカニック	", "	Motorcycle Mechanic	", "MLTSSL", "	TRA	"],
    ["マルチメディアデザイナー	", "	Multimedia Designer	", "Regional", "VETASSESS"],
    ["マルチメディアスペシャリスト	", "	Multimedia Specialist	", "MLTSSL", "	ACS	"],
    ["音楽監督	", "	Music Director	", "STSOL", "VETASSESS"],
    ["音楽プロフェッショナル", "	Music Professionals nec	", "STSOL", "VETASSESS"],
    ["音楽教師（私立授業）", "	Music Teacher (Private Tuition)	", "STSOL", "VETASSESS"],
    ["ミュージシャン（インストゥルメンタル）	", "	Musician (Instrumental)	", "MLTSSL", "VETASSESS"],
    ["自然科学と物理学の専門家", "	Natural and Physical Science Professionals nec	", "MLTSSL", "VETASSESS"],
    ["自然療法士", "	Naturopath	", "STSOL", "VETASSESS"],
    ["造船技師	", "	Naval Architect	", "MLTSSL", "	Engineers Australia	"],
    ["ネットワーク管理者	", "	Network Administrator	", "STSOL", "	ACS	"],
    ["ネットワークアナリスト	", "	Network Analyst	", "STSOL", "	ACS	"],
    ["神経学者	", "	Neurologist	", "MLTSSL", "	MedBA	"],
    ["神経外科医	", "	Neurosurgeon	", "MLTSSL", "	MedBA	"],
    ["新聞または定期的な編集者	", "	Newspaper or Periodical Editor	", "STSOL", "VETASSESS"],
    ["核医学技術者	", "	Nuclear Medicine Technologist	", "MLTSSL", "	ANZSNM	"],
    ["看護師	", "	Nurse Educator	", "STSOL", "	ANMAC	"],
    ["ナースマネージャー	", "	Nurse Manager	", "STSOL", "	ANMAC	"],
    ["ナースプラクティショナー	", "	Nurse Practitioner	", "MLTSSL", "	ANMAC	"],
    ["看護師	", "	Nurse Researcher	", "STSOL", "	ANMAC	"],
    ["植木屋", "	Nurseryperson	", "Regional", "	TRA	"],
    ["看護臨床ディレクター	", "	Nursing Clinical Director	", "MLTSSL", "	ANMAC	"],
    ["栄養士	", "	Nutritionist	", "STSOL", "VETASSESS"],
    ["産科医および婦人科医	", "	Obstetrician and Gynaecologist	", "MLTSSL", "	MedBA	"],
    ["労働安全衛生アドバイザー	", "	Occupational Health and Safety Adviser	", "STSOL", "VETASSESS"],
    ["作業療法士	", "	Occupational Therapist	", "MLTSSL", "	OTC	"],
    ["オペレーションシアターテクニシャン	", "	Operating Theatre Technician	", "Regional", "VETASSESS"],
    ["眼科医	", "	Ophthalmologist	", "MLTSSL", "	MedBA	"],
    ["視力測定医", "	Optometrist	", "MLTSSL", "	OCANZ	"],
    ["組織と方法アナリスト	", "	Organisation and Methods Analyst	", "STSOL", "VETASSESS"],
    ["組織心理学者	", "	Organisational Psychologist	", "MLTSSL", "	APS	"],
    ["整形外科医	", "	Orthopaedic Surgeon	", "MLTSSL", "	MedBA	"],
    ["視能訓練士", "	Orthoptist	", "STSOL", "VETASSESS"],
    ["視能訓練士/歯科技工師", "	Orthotist or Prosthetist	", "MLTSSL", "	AOPA	"],
    ["整骨医", "	Osteopath	", "MLTSSL", "	AOAC	"],
    ["空間科学者	", "	Other Spatial Scientist	", "MLTSSL", "VETASSESS"],
    ["その他スポーツコーチまたはインストラクター	", "	Other Sports Coach or Instructor	", "STSOL", "VETASSESS"],
    ["耳鼻咽喉科医	", "	Otorhinolaryngologist	", "MLTSSL", "	MedBA	"],
    ["小児外科医	", "	Paediatric Surgeon	", "MLTSSL", "	MedBA	"],
    ["小児科医	", "	Paediatrician	", "MLTSSL", "	MedBA	"],
    ["絵画貿易労働者	", "	Painting Trades Worker	", "MLTSSL", "	TRA	"],
    ["板金工	", "	Panelbeater	", "MLTSSL", "	TRA	"],
    ["パン菓子職人", "	Pastrycook	", "STSOL", "	TRA	"],
    ["特許審査官	", "	Patents Examiner	", "STSOL", "VETASSESS"],
    ["病理学者	", "	Pathologist	", "MLTSSL", "	MedBA	"],
    ["病理学コレクター	", "	Pathology Collector	", "Regional", "AIMS"],
    ["パフォーミングアーツ技術者", "	Performing Arts Technicians nec	", "STSOL", "VETASSESS"],
    ["石油エンジニア	", "	Petroleum Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["薬局の技術者	", "	Pharmacy Technician	", "STSOL", "VETASSESS"],
    ["フォトグラファー	", "	Photographer	", "STSOL", "VETASSESS"],
    ["物理学者", "Physicist", "MLTSSL", "VETASSESS(non-medical physicist) / ACPSEM (medical physicists)	"],
    ["理学療法士	", "	Physiotherapist	", "MLTSSL", "	APC	"],
    ["豚の農夫	", "	Pig Farmer	", "STSOL", "VETASSESS"],
    ["プラスチックおよび再建外科医	", "	Plastic and Reconstructive Surgeon	", "MLTSSL", "	MedBA	"],
    ["配管工（一般）	", "	Plumber (General)	", "MLTSSL", "	TRA	"],
    ["足病医", "	Podiatrist	", "MLTSSL", "	APodA/ANZPAC	"],
    ["ポリシーアナリスト	", "	Policy Analyst	", "Regional", "VETASSESS"],
    ["ポリシーと計画マネージャ	", "	Policy and Planning Manager	", "Regional", "VETASSESS"],
    ["郵便局長	", "	Post Office Manager	", "Regional", "VETASSESS"],
    ["家禽農家", "	Poultry Farmer	", "STSOL", "VETASSESS"],
    ["発電プラントオペレーター	", "	Power Generation Plant Operator	", "STSOL", "	TRA	"],
    ["精密計器メーカーおよび修理業者	", "	Precision Instrument Maker and Repairer	", "STSOL", "	TRA	"],
    ["圧力溶接機	", "	Pressure Welder	", "MLTSSL", "	TRA	"],
    ["一次保健機関マネージャー	", "	Primary Health Organisation Manager	", "MLTSSL", "VETASSESS"],
    ["主要製品検査官", "	Primary Products Inspectors nec	", "STSOL", "VETASSESS"],
    ["小学校の先生	", "	Primary School Teacher	", "STSOL", "	AITSL	"],
    ["印刷仕上げ工", "	Print Finisher	", "STSOL", "	TRA	"],
    ["ジャーナリスト	", "	Print Journalist	", "STSOL", "VETASSESS"],
    ["印刷工", "	Printing Machinist	", "STSOL", "	TRA	"],
    ["プライベートチューター/教師", "	Private Tutors and Teachers nec	", "STSOL", "VETASSESS"],
    ["調達マネージャー	", "	Procurement Manager	", "Regional", "AIM"],
    ["プロダクションマネージャー（林業）	", "	Production Manager (Forestry)	", "STSOL", "VETASSESS"],
    ["プロダクションマネージャー（製造）	", "	Production Manager (Manufacturing)	", "STSOL", "VETASSESS"],
    ["プロダクションマネージャー（マイニング）	", "	Production Manager (Mining)	", "STSOL", "VETASSESS"],
    ["生産またはプラントエンジニア	", "	Production or Plant Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["プログラムディレクター（テレビまたはラジオ）	", "	Program Director (Television or Radio)	", "STSOL", "VETASSESS"],
    ["プログラムまたはプロジェクト管理者	", "	Program or Project Administrator	", "STSOL", "VETASSESS"],
    ["プロジェクトビルダ	", "	Project Builder	", "Regional", "VETASSESS"],
    ["プロパティマネージャー	", "	Property Manager	", "Regional", "VETASSESS"],
    ["精神科医	", "	Psychiatrist	", "MLTSSL", "	MedBA	"],
    ["心理学者", "	Psychologists nec	", "MLTSSL", "	APS	"],
    ["サイコセラピスト	", "	Psychotherapist	", "STSOL", "VETASSESS"],
    ["広報マネージャー	", "	Public Relations Manager	", "Regional", "AIM"],
    ["広報プロフェッショナル	", "	Public Relations Professional	", "STSOL", "VETASSESS"],
    ["品質保証マネージャー	", "	Quality Assurance Manager	", "STSOL", "VETASSESS"],
    ["数量検査員	", "	Quantity Surveyor	", "MLTSSL", "	AIQS	"],
    ["放射線腫瘍学者	", "	Radiation Oncologist	", "MLTSSL", "	MedBA	"],
    ["無線通信技術者	", "	Radiocommunications Technician	", "MLTSSL", "	TRA	"],
    ["不動産代理人	", "	Real Estate Representative	", "Regional", "VETASSESS"],
    ["レコードマネージャ	", "	Records Manager	", "STSOL", "VETASSESS"],
    ["レクリエーションオフィサー	", "	Recreation Officer	", "STSOL", "VETASSESS"],
    ["採用コンサルタント	", "	Recruitment Consultant	", "STSOL", "VETASSESS"],
    ["地域教育マネージャー	", "RegionalEducation Manager	", "Regional", "VETASSESS"],
    ["登録看護師（高齢者ケア）	", "	Registered Nurse (Aged Care)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（児童および家族の健康）	", "	Registered Nurse (Child and Family Health)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（地域保健）	", "	Registered Nurse (Community Health)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（クリティカルケアと緊急事態）	", "	Registered Nurse (Critical Care and Emergency)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（発達障害）	", "	Registered Nurse (Developmental Disability)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（障害者およびリハビリ）	", "	Registered Nurse (Disability and Rehabilitation)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（医療従事者）	", "	Registered Nurse (Medical Practice)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（医療）	", "	Registered Nurse (Medical)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（メンタルヘルス）	", "	Registered Nurse (Mental Health)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（小児科医）	", "	Registered Nurse (Paediatrics)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（周術期）	", "	Registered Nurse (Perioperative)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師（外科）	", "	Registered Nurse (Surgical)	", "MLTSSL", "	ANMAC	"],
    ["登録看護師	", "	Registered Nurses nec	", "MLTSSL", "	ANMAC	"],
    ["リハビリカウンセラー	", "	Rehabilitation Counsellor	", "STSOL", "VETASSESS"],
    ["腎医専門医	", "	Renal Medicine Specialist	", "MLTSSL", "	MedBA	"],
    ["研究開発マネージャー	", "	Research and Development Manager	", "STSOL", "VETASSESS"],
    ["居住医療士	", "	Resident Medical Officer	", "STSOL", "	MedBA	"],
    ["住宅ケアオフィサー	", "	Residential Care Officer	", "STSOL", "VETASSESS"],
    ["リテールバイヤー	", "	Retail Buyer	", "STSOL", "VETASSESS"],
    ["小売薬師	", "	Retail Pharmacist	", "STSOL", "	APharmC	"],
    ["リウマチ学者	", "	Rheumatologist	", "MLTSSL", "	MedBA	"],
    ["屋根配管	", "	Roof Plumber	", "MLTSSL", "	TRA	"],
    ["ルーフタイル	", "	Roof Tiler	", "STSOL", "	TRA	"],
    ["安全性検査官	", "	Safety Inspector	", "Regional", "VETASSESS"],
    ["セールス＆マーケティングマネージャー	", "	Sales and Marketing Manager	", "STSOL", "AIM"],
    ["学校長	", "	School Principal	", "STSOL", "VETASSESS"],
    ["科学技術者", "	Science Technicians nec	", "STSOL", "VETASSESS"],
    ["中学校の教師	", "	Secondary School Teacher	", "MLTSSL", "	AITSL	"],
    ["羊の農夫	", "	Sheep Farmer	", "STSOL", "VETASSESS"],
    ["板金取引労働者	", "	Sheetmetal Trades Worker	", "MLTSSL", "	TRA	"],
    ["船のマスター	", "	Ship's Master	", "Regional", "	AMSA	"],
    ["造船所	", "	Shipwright	", "MLTSSL", "	TRA	"],
    ["サイン・ライター	", "	Signwriter	", "STSOL", "	TRA	"],
    ["小型エンジンメカニック	", "	Small Engine Mechanic	", "MLTSSL", "	TRA	"],
    ["冬季スポーツインストラクター	", "	Snowsport Instructor	", "STSOL", "VETASSESS"],
    ["ソーシャルプロフェッショナル", "	Social Professionals nec	", "STSOL", "VETASSESS"],
    ["ソーシャルワーカー	", "	Social Worker	", "MLTSSL", "	AASW	"],
    ["ソフトウェアとアプリケーションプログラマ", "	Software and Applications Programmers nec	", "MLTSSL", "	ACS	"],
    ["ソフトウェアエンジニア	", "	Software Engineer	", "MLTSSL", "	ACS	"],
    ["ソフトウェアテスター	", "	Software Tester	", "STSOL", "	ACS	"],
    ["弁護士	", "	Solicitor	", "MLTSSL", "	A legal admissions authority of a State or Territory	"],
    ["ソリッドプラストラー	", "	Solid Plasterer	", "MLTSSL", "	TRA	"],
    ["音波検査者", "	Sonographer	", "MLTSSL", "	ASMIRT	"],
    ["サウンドテクニシャン	", "	Sound Technician	", "STSOL", "	TRA	"],
    ["特別教育教師	", "	Special Education Teachers nec	", "MLTSSL", "	AITSL	"],
    ["特別教師	", "	Special Needs Teacher	", "MLTSSL", "	AITSL	"],
    ["スペシャリスト・マネージャー", "	Specialist Managers nec	", "STSOL", "VETASSESS"],
    ["専門医（一般医学）	", "	Specialist Physician (General Medicine)	", "MLTSSL", "	MedBA	"],
    ["スペシャリスト医師", "	Specialist Physicians nec	", "MLTSSL", "	MedBA	"],
    ["音声病理学者	", "	Speech Pathologist	", "MLTSSL", "	SPA	"],
    ["スポーツ管理者	", "	Sports Administrator	", "Regional", "VETASSESS"],
    ["スポーツセンターマネージャー	", "	Sports Centre Manager	", "Regional", "VETASSESS"],
    ["スポーツ開発責任者	", "	Sports Development Officer	", "STSOL", "VETASSESS"],
    ["スポーツスポンサーズ", "	Sportspersons nec	", "STSOL", "VETASSESS"],
    ["舞台主任", "	Stage Manager	", "STSOL", "VETASSESS"],
    ["統計", "	Statistician	", "MLTSSL", "VETASSESS"],
    ["ストックブローキングディーラー	", "	Stockbroking Dealer	", "STSOL", "VETASSESS"],
    ["石工	", "	Stonemason	", "MLTSSL", "	TRA	"],
    ["構造エンジニア	", "	Structural Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["学生カウンセラー	", "	Student Counsellor	", "STSOL", "VETASSESS"],
    ["サトウキビの栽培者	", "	Sugar Cane Grower	", "STSOL", "VETASSESS"],
    ["供給管理マネージャー	", "	Supply and Distribution Manager	", "STSOL", "AIM"],
    ["外科医（一般）	", "	Surgeon (General)	", "MLTSSL", "	MedBA	"],
    ["測量または空間科学技術者	", "	Surveying or Spatial Science Technician	", "Regional", "VETASSESS"],
    ["測量	", "	Surveyor	", "MLTSSL", "	SSSI	"],
    ["スイミングコーチまたはインストラクター	", "	Swimming Coach or Instructor	", "STSOL", "VETASSESS"],
    ["システム管理者	", "	Systems Administrator	", "STSOL", "	ACS	"],
    ["システムアナリスト	", "	Systems Analyst	", "MLTSSL", "	ACS	"],
    ["税務会計士	", "	Taxation Accountant	", "MLTSSL", "CAANZ/CPAA/IPA"],
    ["英語教師(英語を話さない生徒向け)", "	Teacher of English to Speakers of Other Languages	", "STSOL", "VETASSESS"],
    ["聴覚障がい者の教師	", "	Teacher of the Hearing Impaired	", "MLTSSL", "	AITSL	"],
    ["視力障害の教師	", "	Teacher of the Sight Impaired	", "MLTSSL", "	AITSL	"],
    ["ケーブル組み付け工", "	Technical Cable Jointer	", "MLTSSL", "	TRA	"],
    ["技術指導者	", "	Technical Director	", "STSOL", "VETASSESS"],
    ["テクニカルセールス担当者", "	Technical Sales Representatives nec	", "STSOL", "VETASSESS"],
    ["テクニカルライター	", "	Technical Writer	", "STSOL", "VETASSESS"],
    ["電気通信技術者	", "	Telecommunications Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["電気通信フィールドエンジニア	", "	Telecommunications Field Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["電気通信事業者	", "	Telecommunications Linesworker	", "STSOL", "	TRA	"],
    ["電気通信ネットワークエンジニア	", "	Telecommunications Network Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["テレコミュニケーションネットワークプランナー	", "	Telecommunications Network Planner	", "MLTSSL", "	Engineers Australia	"],
    ["電気通信技術者または技術者	", "	Telecommunications Technical Officer or Technologist	", "MLTSSL", "	Engineers Australia	"],
    ["テレビジャーナリスト	", "	Television Journalist	", "STSOL", "VETASSESS"],
    ["テニスコーチ	", "	Tennis Coach	", "STSOL", "VETASSESS"],
    ["テキスタイル、衣類、履物機械	", "	Textile, Clothing and Footwear Mechanic	", "STSOL", "	TRA	"],
    ["胸部医療専門医	", "	Thoracic Medicine Specialist	", "MLTSSL", "	MedBA	"],
    ["道具メーカー	", "	Toolmaker	", "STSOL", "	TRA	"],
    ["中国の伝統医師", "	Traditional Chinese Medicine Practitioner	", "STSOL", "	Chinese Medicine Board of Australia	"],
    ["翻訳者	", "	Translator	", "Regional", "	NAATI	"],
    ["運送会社マネージャー	", "	Transport Company Manager	", "STSOL", "VETASSESS"],
    ["輸送エンジニア	", "	Transport Engineer	", "MLTSSL", "	Engineers Australia	"],
    ["大学教授	", "	University Lecturer	", "MLTSSL", "VETASSESS"],
    ["家具職人", "	Upholsterer	", "STSOL", "	TRA	"],
    ["都市計画と地域プランナー	", "	Urban andRegionalPlanner	", "STSOL", "VETASSESS"],
    ["泌尿器科医	", "	Urologist	", "MLTSSL", "	MedBA	"],
    ["家具製造販売業者", "	Valuer	", "MLTSSL", "VETASSESS"],
    ["血管外科医	", "	Vascular Surgeon	", "MLTSSL", "	MedBA	"],
    ["野菜栽培者	", "	Vegetable Grower	", "STSOL", "VETASSESS"],
    ["車体ビルダー	", "	Vehicle Body Builder	", "STSOL", "	TRA	"],
    ["車両ペインタ	", "	Vehicle Painter	", "Regional", "	TRA	"],
    ["車両トリマー	", "	Vehicle Trimmer	", "STSOL", "	TRA	"],
    ["獣医	", "	Veterinarian	", "MLTSSL", "	AVBC	"],
    ["獣医看護師	", "	Veterinary Nurse	", "STSOL", "VETASSESS"],
    ["ビデオプロデューサ	", "	Video Producer	", "STSOL", "VETASSESS"],
    ["視覚芸術と工芸の専門家", "	Visual Arts and Crafts Professionals nec	", "STSOL", "VETASSESS"],
    ["職業教育教師	", "	Vocational Education Teacher	", "Regional", "VETASSESS"],
    ["壁と床のタイル	", "	Wall and Floor Tiler	", "MLTSSL", "	TRA	"],
    ["時計、時計メーカー、修理業者	", "	Watch and Clock Maker and Repairer	", "STSOL", "	TRA	"],
    ["Web管理者	", "	Web Administrator	", "STSOL", "	ACS	"],
    ["ウェブデザイナー	", "	Web Designer	", "STSOL", "VETASSESS"],
    ["ウェブ開発者	", "	Web Developer	", "STSOL", "	ACS	"],
    ["溶接機（ファーストクラス）	", "	Welder (First Class)	", "MLTSSL", "	TRA	"],
    ["福祉センター長	", "	Welfare Centre Manager	", "MLTSSL", "ACWA"],
    ["福祉ワーカー	", "	Welfare Worker	", "STSOL", "ACWA"],
    ["ワインメーカー	", "	Wine Maker	", "Regional", "VETASSESS"],
    ["木工機械	", "	Wood Machinist	", "STSOL", "	TRA	"],
    ["木工機械と他の木材貿易労働者", "	Wood Machinists and Other Wood Trades Workers nec	", "STSOL", "	TRA	"],
    ["職場リレーションズアドバイザー	", "	Workplace Relations Adviser	", "Regional", "VETASSESS"],
    ["若年労働者", "	Youth Worker	", "STSOL", "ACWA"],
    ["動物園", "	Zookeeper	", "Regional", "VETASSESS"],
    ["動物学者", "	Zoologist	", "MLTSSL", "VETASSESS"],
];
